//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogApp.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoogApp.Translations.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added you to circles.
        /// </summary>
        public static string addedYouToCircles {
            get {
                return ResourceManager.GetString("addedYouToCircles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relationship.
        /// </summary>
        public static string aRelationship {
            get {
                return ResourceManager.GetString("aRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you going?.
        /// </summary>
        public static string areYouGoing {
            get {
                return ResourceManager.GetString("areYouGoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic information.
        /// </summary>
        public static string basicInfo {
            get {
                return ResourceManager.GetString("basicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best.
        /// </summary>
        public static string best {
            get {
                return ResourceManager.GetString("best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSTS.
        /// </summary>
        public static string bigPosts {
            get {
                return ResourceManager.GetString("bigPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bragging rights.
        /// </summary>
        public static string bragging {
            get {
                return ResourceManager.GetString("bragging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy.
        /// </summary>
        public static string buy {
            get {
                return ResourceManager.GetString("buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By signing to Google+ service, you agree to Google Terms of Service..
        /// </summary>
        public static string bySigning {
            get {
                return ResourceManager.GetString("bySigning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camera.
        /// </summary>
        public static string camera {
            get {
                return ResourceManager.GetString("camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categories.
        /// </summary>
        public static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to circles.
        /// </summary>
        public static string circles {
            get {
                return ResourceManager.GetString("circles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a civil union.
        /// </summary>
        public static string civilUnion {
            get {
                return ResourceManager.GetString("civilUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commented.
        /// </summary>
        public static string commented {
            get {
                return ResourceManager.GetString("commented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commented your post.
        /// </summary>
        public static string commentedYourPost {
            get {
                return ResourceManager.GetString("commentedYourPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to communities.
        /// </summary>
        public static string communities {
            get {
                return ResourceManager.GetString("communities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communities.
        /// </summary>
        public static string communitiesTitle {
            get {
                return ResourceManager.GetString("communitiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMUNITY.
        /// </summary>
        public static string community {
            get {
                return ResourceManager.GetString("community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s complicated.
        /// </summary>
        public static string complicated {
            get {
                return ResourceManager.GetString("complicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribute to.
        /// </summary>
        public static string contributeTo {
            get {
                return ResourceManager.GetString("contributeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string currentContributeTo {
            get {
                return ResourceManager.GetString("currentContributeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently.
        /// </summary>
        public static string currently {
            get {
                return ResourceManager.GetString("currently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dating.
        /// </summary>
        public static string dating {
            get {
                return ResourceManager.GetString("dating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to did something that I don&apos;t know xD.
        /// </summary>
        public static string didSomething {
            get {
                return ResourceManager.GetString("didSomething", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a domestic partnership.
        /// </summary>
        public static string domesticPartnership {
            get {
                return ResourceManager.GetString("domesticPartnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t want to say.
        /// </summary>
        public static string dontSay {
            get {
                return ResourceManager.GetString("dontSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this activity?.
        /// </summary>
        public static string doYouReallyWant {
            get {
                return ResourceManager.GetString("doYouReallyWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit comment.
        /// </summary>
        public static string editComment {
            get {
                return ResourceManager.GetString("editComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit post.
        /// </summary>
        public static string editPost {
            get {
                return ResourceManager.GetString("editPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string education {
            get {
                return ResourceManager.GetString("education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment.
        /// </summary>
        public static string employment {
            get {
                return ResourceManager.GetString("employment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engaged.
        /// </summary>
        public static string engaged {
            get {
                return ResourceManager.GetString("engaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter token:.
        /// </summary>
        public static string enterToken {
            get {
                return ResourceManager.GetString("enterToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string events {
            get {
                return ResourceManager.GetString("events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVENT.
        /// </summary>
        public static string eventTitle {
            get {
                return ResourceManager.GetString("eventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone.
        /// </summary>
        public static string everyone {
            get {
                return ResourceManager.GetString("everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;(.
        /// </summary>
        public static string faggot {
            get {
                return ResourceManager.GetString("faggot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string friends {
            get {
                return ResourceManager.GetString("friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your FULL credentials..
        /// </summary>
        public static string fullCredentials {
            get {
                return ResourceManager.GetString("fullCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gave +1 for your comment.
        /// </summary>
        public static string gavePlusOne {
            get {
                return ResourceManager.GetString("gavePlusOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get more.
        /// </summary>
        public static string getMore {
            get {
                return ResourceManager.GetString("getMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to post.
        /// </summary>
        public static string git {
            get {
                return ResourceManager.GetString("git", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to google+ in browser.
        /// </summary>
        public static string googleBrowser {
            get {
                return ResourceManager.GetString("googleBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google+ client for Windows Phone.
        /// </summary>
        public static string googlePlus {
            get {
                return ResourceManager.GetString("googlePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OP is a faggot (or report bug).
        /// </summary>
        public static string imFaggot {
            get {
                return ResourceManager.GetString("imFaggot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a relationship.
        /// </summary>
        public static string inRelationship {
            get {
                return ResourceManager.GetString("inRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro.
        /// </summary>
        public static string intro {
            get {
                return ResourceManager.GetString("intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link.
        /// </summary>
        public static string link {
            get {
                return ResourceManager.GetString("link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter link (with &quot;http://) and tap OK to continue..
        /// </summary>
        public static string linkContent {
            get {
                return ResourceManager.GetString("linkContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string links {
            get {
                return ResourceManager.GetString("links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with logging. Make sure you have a internet connectivity and  Google+ service enabled in your Google account..
        /// </summary>
        public static string loginError {
            get {
                return ResourceManager.GetString("loginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for.
        /// </summary>
        public static string lookingFor {
            get {
                return ResourceManager.GetString("lookingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mark as read.
        /// </summary>
        public static string markAsRead {
            get {
                return ResourceManager.GetString("markAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        public static string married {
            get {
                return ResourceManager.GetString("married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe.
        /// </summary>
        public static string maybe {
            get {
                return ResourceManager.GetString("maybe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mentioned you.
        /// </summary>
        public static string metionedYou {
            get {
                return ResourceManager.GetString("metionedYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networking.
        /// </summary>
        public static string networking {
            get {
                return ResourceManager.GetString("networking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new post.
        /// </summary>
        public static string newPost {
            get {
                return ResourceManager.GetString("newPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicks:.
        /// </summary>
        public static string nicks {
            get {
                return ResourceManager.GetString("nicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noooooo!.
        /// </summary>
        public static string nooo {
            get {
                return ResourceManager.GetString("nooo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No specified.
        /// </summary>
        public static string noSpecified {
            get {
                return ResourceManager.GetString("noSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifications.
        /// </summary>
        public static string notifications {
            get {
                return ResourceManager.GetString("notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        public static string occupation {
            get {
                return ResourceManager.GetString("occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a open relationship.
        /// </summary>
        public static string openRelationship {
            get {
                return ResourceManager.GetString("openRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string otherGender {
            get {
                return ResourceManager.GetString("otherGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other profiles.
        /// </summary>
        public static string otherProfiles {
            get {
                return ResourceManager.GetString("otherProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past.
        /// </summary>
        public static string pastContributeTo {
            get {
                return ResourceManager.GetString("pastContributeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string people {
            get {
                return ResourceManager.GetString("people", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo.
        /// </summary>
        public static string photo {
            get {
                return ResourceManager.GetString("photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places.
        /// </summary>
        public static string places {
            get {
                return ResourceManager.GetString("places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gave +1 for your post.
        /// </summary>
        public static string plusForYourPost {
            get {
                return ResourceManager.GetString("plusForYourPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to posted.
        /// </summary>
        public static string posted {
            get {
                return ResourceManager.GetString("posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to posted in community.
        /// </summary>
        public static string postedInCommunity {
            get {
                return ResourceManager.GetString("postedInCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post in:.
        /// </summary>
        public static string postIn {
            get {
                return ResourceManager.GetString("postIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to post in community.
        /// </summary>
        public static string postInCommunity {
            get {
                return ResourceManager.GetString("postInCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting....
        /// </summary>
        public static string posting {
            get {
                return ResourceManager.GetString("posting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to posts.
        /// </summary>
        public static string posts {
            get {
                return ResourceManager.GetString("posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string postsTitle {
            get {
                return ResourceManager.GetString("postsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string previous {
            get {
                return ResourceManager.GetString("previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy:.
        /// </summary>
        public static string privacy {
            get {
                return ResourceManager.GetString("privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string recent {
            get {
                return ResourceManager.GetString("recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        public static string relationship {
            get {
                return ResourceManager.GetString("relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reply.
        /// </summary>
        public static string reply {
            get {
                return ResourceManager.GetString("reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report bug.
        /// </summary>
        public static string reportBug {
            get {
                return ResourceManager.GetString("reportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reshare.
        /// </summary>
        public static string reshare {
            get {
                return ResourceManager.GetString("reshare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results.
        /// </summary>
        public static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string signIn {
            get {
                return ResourceManager.GetString("signIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign out.
        /// </summary>
        public static string signOut {
            get {
                return ResourceManager.GetString("signOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string single {
            get {
                return ResourceManager.GetString("single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string skills {
            get {
                return ResourceManager.GetString("skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story.
        /// </summary>
        public static string story {
            get {
                return ResourceManager.GetString("story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stream.
        /// </summary>
        public static string stream {
            get {
                return ResourceManager.GetString("stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagline.
        /// </summary>
        public static string tagline {
            get {
                return ResourceManager.GetString("tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap OK to continue..
        /// </summary>
        public static string tapTo {
            get {
                return ResourceManager.GetString("tapTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text:.
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred. Contact with developer..
        /// </summary>
        public static string unexpected {
            get {
                return ResourceManager.GetString("unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        public static string uploading {
            get {
                return ResourceManager.GetString("uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By using this software you agree to Google+ Terms and Conditiions..
        /// </summary>
        public static string usingThisSoftware {
            get {
                return ResourceManager.GetString("usingThisSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widowed.
        /// </summary>
        public static string widowed {
            get {
                return ResourceManager.GetString("widowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        public static string work {
            get {
                return ResourceManager.GetString("work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOL, you typed wrong credentials. Try again..
        /// </summary>
        public static string wrongCredentials {
            get {
                return ResourceManager.GetString("wrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string you {
            get {
                return ResourceManager.GetString("you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your circles.
        /// </summary>
        public static string yourCircles {
            get {
                return ResourceManager.GetString("yourCircles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your profile.
        /// </summary>
        public static string yourProfile {
            get {
                return ResourceManager.GetString("yourProfile", resourceCulture);
            }
        }
    }
}
